### ISSUE TITLE
Statistic 7강- 도박꾼의 파산 문제와 확률변수 (Gambler's Ruin and Random Variables) 질문

### ISSUE THREAD

**Issue by lolstatbeta** [IPCVLabEdu/flipped_learning#12]
공6 스터디 진행 중 모두가 이해하지 못하고 넘어간 부분 질문합니다!

두 해가 x = 1, q/p 인거 까진 이해를 했는데 이후, 
1) 23:24 --> pi의 식이 어떻게 나오게 되는지

2) Pi가 있다고 할 때, P0=0은 이해가 되는데 Pn=1인 경우 어떻게 저렇게 넘어가는건가요??

![image](https://user-images.githubusercontent.com/38774597/51457827-3996e100-1d96-11e9-93fa-9cc6d08ba23a.png)

혹시 아시는분이 계시면 알려주세요~

**Comment by heefe92** [comment]
B= -A라는것을 바로 위에 식에서 알아냈기때문에
A+B(q/p)^N = A-A(q/p)^N 입니다.

**Comment by heefe92** [comment]
pi식이 1)처럼 나오는 이유는
계차방정식의 풀이에 의해 저렇게나오는거예요!

**Comment by heefe92** [comment]
p0 = 0
pN = 1
이란것은 이미 명확한 사실입니다!
내가 0원을 들고서 게임하면 이길확률은 0이고
N원을 들고 게임하면 이길확률은 1이니까요

**Comment by lolstatbeta** [comment]
오 2)는 이해했습니다~ 1)은 계차방정식의 풀이에 의해 나온다는게 
pi = x^i 로 가정해서 나온 해를 통해서 선형결합으로 일반해를 세울 수 있다는 풀이에 의해서 나오게 된 식인가요?? 
x^i의 해가 1, q/p 엿는데 가정한 x^i의 해로 계차방정식 pi의 식을 어떻게 만든건지가 이해가 안됩니다.

**Comment by heefe92** [comment]
23분9초에 나오는 내용인데 교수님께서 "일반적으로 계차방정식에서 다항식의 해를 찾아 모두 다르다면 일반해는 그 해의 선형 결합이 됩니다"라고합니다! 
https://en.wikipedia.org/wiki/Linear_difference_equation
위키피디아를 찾아보니 일반적으로 계차방정식이 있을 때 pi=x^i로 치환하여 푸네용..
