### ISSUE TITLE
CS231N 4강 - Jacobian 행렬과 Vectorized Example 질문

### ISSUE THREAD

**Issue by fool8474** [IPCVLabEdu/flipped_learning#19]
CS231N 4강을 보면 Jacobian 행렬에 대한 이야기가 많이 나오는데,
이 개념에 대해 잘 몰라서 W,x가 행렬로 되어있는 예시의 Case에서 이해하기가 어려웠습니다.

![image](https://user-images.githubusercontent.com/28250401/51899461-62525280-23f6-11e9-9b3c-a665f94c75dd.png)

Jacobian 행렬이 뭔지, 왜 사용하는지
그리고 저 W,x가 행렬인 경우의 역전파 연산 과정에 설명해주셨으면 좋겠습니다.

![image](https://user-images.githubusercontent.com/28250401/51899543-962d7800-23f6-11e9-9b06-6c066c517d88.png)
Jacobian 행렬

**Comment by dxdiag20** [comment]
자코비안이 다변수 미분할때 쓰이는 걸로 알고 있어요
행렬 계산하는데 변수가 다양하닌깐 일반 미분식으로는 안되고 자코비안 행렬을 써야 미분 값을 구할 수 잇다는 걸로 알고 있습니다. 이거를 자세하게 이해할려면 아마 대학원에서 다룬다고 알고있어요

**Comment by fool8474** [comment]
아 그런 개념이군요. 감사합니다!
