### ISSUE TITLE
Statistic 9강 - E(X1) == E(X5)가 이해가 안됩니다.

### ISSUE THREAD

**Issue by heefe92** [IPCVLabEdu/flipped_learning#21]
X=(ace카드의 갯수)일 때, Xi를 지시확률변수(1<=i<=5)로 두면 
E(X) = E( X1 + X2 + X3 + X4 + X5 ) =E( X1 ) + E( X2 ) + E( X3 ) + E( X4 ) + E( X5 )
이렇게 나옵니다.
이 때 E(X1) == E(X5) 라고 하면서
E( X1 ) + E( X2 ) + E( X3 ) + E( X4 ) + E( X5 ) = 5*E( X1 )
라고 설명합니다.
이 사건은 독립적이지 않은데 왜 위에식이 성립하나요?
P(X1) != P(X5) 라고 생각하는 이유는 P(X1)은 4/52라고 생각하지만 P(X5)는 앞에 순서에서 나온 에이스의 갯수에 따라 달라진다고 생각합니다. 
에이스가 앞의 네번의 순서에서 k장 나왔다면 P(X5)= (4-k)/48 아닌가요?

**Comment by TaeMinJoo** [comment]
😁😃😆😋😀🤣😅😊😍😙🙂👏👏🎉🎉🎉🎉

**Comment by TaeMinJoo** [comment]
4*3*2  + 4*48*3 + 48*4*3 + 48*47*4                  1
P(X3) 도       -------------------------------------------   =       ----    으로 같네요
                                  52 * 51 * 50                                            13

**Comment by TaeMinJoo** [comment]
![123123](https://user-images.githubusercontent.com/27275328/52036140-a1f07a00-256f-11e9-9eb9-8a28ed2720f9.PNG)

**Comment by TaeMinJoo** [comment]
😁😃😆😋😀🤣😅😊😍😙🙂👏👏🎉🎉🎉🎉
