### ISSUE TITLE
통계 10강 

### ISSUE THREAD

**Issue by AI-MD** [IPCVLabEdu/flipped_learning#23]
음 이항분포와 9강 마지막에 나온 기하분포의 연결고리가 잘 이해 안됩니다.

**Comment by dxdiag20** [comment]
음이항분포에서 r=1이 기하분포인 경우입니다. 이거를 이용해서 분산, 평균 계산을 좀 더 쉽게 할수있는 걸로 알고있습니다. 분포끼리 서로 모수값만 조정하면 서로 이어지는 경우가 많아서 나중에 계산 처리가 좀 더 수월한 경우가 있습니다.
