### ISSUE TITLE
CS231N 6강 - dead ReLU, Xavier initialization

### ISSUE THREAD

**Issue by fool8474** [IPCVLabEdu/flipped_learning#27]
![image](https://user-images.githubusercontent.com/28250401/52769250-1ac4fb00-3073-11e9-9efe-a50d100c44c8.png)
1 ReLU가 dead가 되는 상황에 대해 설명해주는 부분입니다.  
이 사진에서 data cloud가 training data라고 하는데,  
저기서 active ReLU나 dead ReLU가 왜 active나 dead가 되는지 모르겠습니다  
  
  
![image](https://user-images.githubusercontent.com/28250401/52769597-12b98b00-3074-11e9-817e-b617b16ce826.png)
2 Xavier initialization에 대한 설명 부분입니다.  
입력의 수에 따라 가중치를 조정하여 분산을 맞춰주는거라고 대충 이해했는데, 정확히 이해가 안갑니다.
이에 대해 이해하신 분이 좀 더 자세히 알려주셨으면 좋겠습니다.

**Comment by jungin500** [comment]
# 스터디 의견
1. DATA CLOUD에서 멀어질수록 값이 작아짐 => ReLU에서 0 이하로 떨어지므로 Gradient vanishing problem이 발생함 (=dead ReLU)  

2. 초기화의 개념을 좀 더 생각해볼 필요가 있음.  
초기화 문제에 대해 생각하는 이유는 **1. local minimum보다 global minimum에 접근하는 알고리즘을 만들기 위해서** **2. inefficient한 global minimum에 접근하는 초기값을 피하기 위해서**임.
Xavier init.와 같은 부분은 수학적 지식이 많이 필요해 조금더 생각이 필요할 듯

**Comment by fool8474** [comment]
@jungin500 고맙습니다!~~!~!@@@@!!!
